# Oefenboek op het gebruik van Numpy

Deze oefenboekjes bevatten oefeningen om te leren (leeroefeningen). We gaan er dus vanuit dat je op dit punt nog niet veel kennis hebt over de deze topic. Ze zijn bedoeld om de leerstof nog te leren begrijpen en **niet** om te testen of je de leerstof al onder de knie hebt. Daarvoor hebben we een ander soort oefeningen.

## Oefeningen op Numpy arrays

Maak eerst de oefenboekjes op Python alvorens je hier aan begint. Importeer nu eerst de juiste libraries zodat je aan de slag kan.

```python
import numpy as np
```

In [2185]:
import numpy as np

### Oefening 1 - Eenvoudige Numpy arrays aanmaken

De eenvoudigste manier om een Numpy `array` aan te maken is om te vertrekken van Python `list`. Dat kan bv. zo:

```python
import numpy as np     # Niet vergeten om Numpy te importeren met alias np.

lijst = [1,2,3,4,5,6]
data = np.array(lijst)
```
Je kan nu afvragen wat het nut is van een Numpy `array` t.o.v. een klassieke Python `list`. Ze hebben beide hun voor -en nadelen. Zo zijn Python lists flexibeler als het aankomt op datatypes en uitbreiding (ze kunnen verschillende datatypes bevatten, en je kan ze makkelijker groter of kleiner maken). Numpy arrays daarentegen kunnen dat niet. De gegevens in een Numpy array moeten altijd van hetzelfde datatype zijn (bv. allemaal `int`), en ze zijn immutable waardoor je ze niet groter of kleiner kan maken. Toch hebben Numpy arrays enkele troeven in huis waarvan de belangrijkste hun **broadcasting** eigenschap is. Wat dat is, leer je hier.

Maak nu bovenstaand Numpy-array object aan met de naam *data* met daarin deze Python `list` van waarden `[1,2,3,4,5,6]`. Je mag ook een `range` gebruiken.

In [2186]:
data = np.array([1,2,3,4,5,6])
print(data)

[1 2 3 4 5 6]


Een Numpy array is een tabel met zoveel dimensies als je maar wil.Je kan de dimensieinformatie opvragen met de eigenschap `.shape`. 

Een shape is een Python <a href="https://realpython.com/python-lists-tuples/#python-tuples">tuple</a>. Je zal tuples nog heel vaak tegenkomen.

Wat is de shape van je zonet gemaakte Numpy array?

*Nota: Je zal merken dat de `tuple` er een beetje vreemd uit ziet. Dat komt omdat deze array maar 1 dimensie heeft en tuple minstens twee waarden moet bevatten*

In [2187]:
print(data.shape)
# (6,)

(6,)


Zoals hierboven al aangehaald heeft een array altijd één bepaald datatype. Het datatype van een array kan je opvragen met de `.dtype`-eigenschap.

Vraag nu het datatype op van je array?

In [2188]:
print(data.dtype)
# int32

int32


Maak nu een nieuwe array aan met de volgende commando's:
* `np.array([1.0,2.0,3.0,4.0])`
* `np.array([1.0,2.0,3.0,4.0], dtype=int)`

Wat is het verschil?

In [2189]:
test1 = np.array([1.0,2.0,3.0,4.0])
test2 = np.array([1.0,2.0,3.0,4.0], dtype=int)
print(test1.dtype)
print(test2.dtype)
# test1 = float64
# test1 = int32

float64
int32


Je kan elementen uit de array selecteren m.b.v. vierkante haakjes `[]` met daartussen een of meerdere indexen. Je mag daarbij ook gebruikmaken van Python <a href="https://realpython.com/lessons/indexing-and-slicing/">`slices`</a>. Met slices kan je ook per twee tellen of achteruit tellen bv. 

Hieronder zie je enkele tips van hoe je commando kan gebruiken. 

```python
a[1]
a[1:3]
a[[1,3,5]] 
``` 

Haal het tweede element en het tweede t.e.m. het derde element. Dit kan op heel wat verschillende manieren gerealiseerd worden. Probeer zoveel mogelijk zaken uit.

In [2190]:
# 1
print(data[1])
# 2
print(data[1:3])
print(data[[1,2]])

2
[2 3]
[2 3]


### Oefening 2 - Twee dimensionele Numpy arrays

Een 2D array bestaat uit een `list` van een `list` van elementen.

```python
matrix = [
  [],
  [],
  []
]
a = np.array(matrix)
```

Maak een Numpy `array` object aan, genaamd `data`, met drie rijen waavan de waarden gelijk zijn aan:

* rij 1: `[1, 1, 0.83, 1.3]`,
* rij 2: `[2, 4, 0.75, 1.0]`,
* rij 3: `[3, 2, 4.75, 0.2]`

In [2191]:
data = np.array([
    [1, 1, 0.83, 1.3],
    [2, 4, 0.75, 1.0],
    [3, 2, 4.75, 0.2]
])
print(data)

[[1.   1.   0.83 1.3 ]
 [2.   4.   0.75 1.  ]
 [3.   2.   4.75 0.2 ]]



Wat is de shape van dit DataFrame"?

In [2192]:
print(data.shape)
# (3, 4)

(3, 4)


Wat is het datatype van deze array? 

In [2193]:
print(data.dtype)
# float64

float64


Natuurlijk kan je ook uit 2D arrays elementen selecteren m.b.v. vierkante haakjes `[]` met daartussen een of meerdere indexen. 

Hieronder zie je enkele tips van hoe je commando kan gebruiken. 

```python
a[1,1]
a[1:3,3]
a[[1,3,5], 2:4]
``` 

Haal het 2e element op van de 3e rij.
Haal nu het tweede t.e.m. het derde element op van rijen 1 en 2. Dit kan op heel wat verschillende manieren gerealiseerd worden. Probeer weer zoveel mogelijk zaken uit.

In [2194]:
# [0,0] [0,1] [0,2] [0,3]
# [1,0] [1,1] [1,2] [1,3]
# [2,0] [2,1] [2,2] [2,3]
# [3,0] [3,1] [3,2] [3,3]
# 1
print(data[2,1])
# 2
print(data[0:2,1:3])
print() # /n
print(data[[1,2], 1:3])

2.0
[[1.   0.83]
 [4.   0.75]]

[[4.   0.75]
 [2.   4.75]]


### Oefening 3 - Broadcasting begrijpen

Maak twee Numpy arrays, `enen` en `vijven` aan met onderstaande code, en tel ze bij elkaar op.

```python
enen = np.ones(10)        # shape = (10,)
vijven = np.tile(5,10)    # shape = (10,)
enen + vijven             # shape = (10,)
```
Merk op dat de dimensie van deze arrays gelijk zijn. Het zijn 1D arrays met lengte 10.
Print de gemaakte arrays uit evenals hun shapes.

In [2195]:
enen = np.ones(10)            # shape = (10,)
vijven = np.tile(5,10)        # shape = (10,)
enen + vijven                 # shape = (10,)
print(enen)
print(enen.shape)
print() # /n
print(vijven)
print(vijven.shape)
print() # /n
print(enen + vijven)
print((enen + vijven).shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)

[5 5 5 5 5 5 5 5 5 5]
(10,)

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
(10,)


Maak nu twee arrays met onderstaande code

```python
a = np.array([[1,2], 
              [3,4],
              [5,6]])
b = np.array([
              [10,100]
              ])
```

Merk op dat de dimensie van deze arrays **niet meer gelijk** zijn, maar het *laatste deel* van hun shapes zijn wel hetzelfde en dat één van de dimensie ook gelijk is aan 1. Controleer dit door de shapes van deze arrays uit te printen.

In [2196]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

b = np.array([
              [10,100]
              ])

print(a.shape)
print() # /n
print(b.shape)

(3, 2)

(1, 2)


Tel nu de arrays `a` en `b` bij elkaar op en stop het resultaat in variabele `c` en print het resultaat uit. Wat is de shape van nieuwe array? Verklaar in woorden wat er volgens jou gebeurd is.

In [2197]:
c = np.array(a + b)
print(c)
print() # /n
print(c.shape)
# De shape van de nieuwe array c is (3, 2), wat betekent dat het drie rijen en twee kolommen heeft.
# Wat hier gebeurt is dat we de elementen van elke kolom in b optellen bij de overeenkomstige elementen in de
# kolommen van a. Dit resulteert in een nieuwe array c met dezelfde vorm als a en b, waarbij de elementen van b zijn opgeteld bij de elementen van a.

[[ 11 102]
 [ 13 104]
 [ 15 106]]

(3, 2)


Eens kijken of vermenigvuldigen ook werkt?

Vermenigvuldig `a` met `b`.

In [2198]:
d = np.array(a * b)
print(d)
print() # /n
print(d.shape)

[[ 10 200]
 [ 30 400]
 [ 50 600]]

(3, 2)


In de vorige voorbeelden wordt de dimensie van `b` tijdelijk 'opgerekt' tot die van `a` langs de as met dimensie 1, zodat de dimensies overeenkomen. Dit oprekken kan je zelf ook nabootsen met de `repeat`-functie uit Numpy. 

```python
temp = np.repeat(b,3,axis=0)    # wat zou axis=1 doen?
print(temp)
temp.shape
```
*Nota: de `repeat`-functie lijkt op de `tile`-functie maar werkt net iets anders. Probeer zelf de verschillen te vinden door te experimenteren met het herhalen van een volledige Numpy array*



In [2199]:
temp = np.repeat(b,3,axis=0)    # wat zou axis=1 doen? -> Alle rijen gaan in 1D
print(temp)
print(temp.shape)

[[ 10 100]
 [ 10 100]
 [ 10 100]]
(3, 2)


Nu onderzoeken wanneer **broadcasting** niet werkt, zodat je beter kan begrijpen hoe het wel werkt, en tegelijkertijd leren we nog enkele handige functies bij uit de Numpy library (die wel goed werken).

```
a = np.full(shape=(2,4), fill_value=np.pi)       # 2D array met getal pi
b = np.full(shape=(3,1), fill_value=np.exp(1))  # 2D array met getal van Euler
print(a)
print(b)
a+b   
```

Probeer deze code uit en je zal een <font color="red">_Value Error: operands could not be broadcast together</font>_ krijgen.

Zet de foute regel in commentaar en controleer de shapes van `a` en `b`.

In [2200]:
a = np.full(shape=(2,4), fill_value=np.pi)       # 2D array met getal pi
b = np.full(shape=(2,4), fill_value=np.exp(1))  # 2D array met getal van Euler
print(a)
print(a.shape)
print() # /n
print(b)
print(b.shape)
print() # /n
print(a + b)
print((a + b).shape)

[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]
(2, 4)

[[2.71828183 2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183 2.71828183]]
(2, 4)

[[5.85987448 5.85987448 5.85987448 5.85987448]
 [5.85987448 5.85987448 5.85987448 5.85987448]]
(2, 4)


Lees de [uitleg](https://numpy.org/doc/stable/user/basics.broadcasting.html) over wanneer broadcasting wel kan werken op de officiële website van de Numpy library. Broadcasting kan alleen werken indien:

* de laatste dimensie gelijk is
* alle niet-overeenstemmende dimensies gelijk zijn aan de dimensie 1 in de andere array.

Enkele voorbeelden van dimensies waar broadcasting zal **werken** (van bovenstaande link):

```
256 x 256 x 3      # shape van array a
          x 3      # shape van array b
-------------
256 x 256 x 3      # shape van array c
```
```
8 x 1 x 6 x 1      # shape van array a
    7 x 1 x 5      # shape van array b
-------------
8 x 7 x 6 x 5      # shape van array c
```
```
1                  # shape van array a
4                  # shape van array b
-
4                  # shape van array c
```

Voorbeelden waar broadcasting **niet zal werken**:

```
3                  # shape van array a
4                  # shape van array b
-
?                 
```

```
2 x 4              # shape van array a
3 x 1              # shape van array b
-----
?????
```
```
    2 x 1          # shape van array a
8 x 4 x 3          # shape van array b
---------
?????????
```

### Oefening 4 - Numpy arrays vervormen

Een vaak gebruikte functie om arrays te vervormen is `np.reshape`.  Veel algoritmen verwachten namelijk dat de inputdata in een bepaalde vorm staat. Wanneer we neurale netwerken willen trainen die afbeeldingen leren herkennen, zullen we eerst vierkante 2D-matrix van pixels moeten omzetten naar één lange 1D-array.

Zoals de naam al laat vermoeden, kun je met `np.reshape` de **dimensies** van een array **aanpassen**. Uiteraard moeten deze dimensie wijzigingen gebeuren binnen *de mate van het mogelijke*, d.w.z.: alle elementen uit de originele array moeten een nieuwe plaats kunnen krijgen in de nieuwe vorm. Na de hervorming moeten er dus evenveel plaatsen zijn voor alle originele elementen.

**Voorbeelden**

* 1D-array van 10 kun je omzetten naar een 2D-array van 5 x 2
* 2D-array van 5 x 4 kun je omzetten naar een 2D-array van 4 x 5
* 2D-array van 5 x 4 kun je omzetten naar een 1D-array van 20
* 2D-array van 5 x 4 kun je omzetten naar een 2D-array van 10 x 2
* 3D-array van 28 x 28 x 3 kun je omzetten naar een array van 2352
* ...

Naast de **functie** `np.reshape` kan je ook gebruikmaken van de **methode** `.reshape()`. Ze doet hetzelfde, maar je roept ze gewoon op vanaf de array zelf.  Een laatste nuttige tip is dat je altijd **één dimensie minder** hoeft op te geven van de nieuwe vorm. Als je van 2D naar een andere 2D wil gaan, kan je één dimensie op geven en de andere op -1 zetten. Numpy vindt dan zelf de juiste waarde voor die ontbrekende dimensie. Het maakt ook niet uit welke dimensie je achterwege laat.

**Voorbeeld**

* Een 1D-array van 6 kun je omzetten naar een 2D-array van 3 x 2 door mee te geven dat er 3 rijen moeten zijn. Numpy berekent zelf dat er dan 2 kolommen zullen zijn.
* Een 1D-array van 5 x 4 kun je omzetten naar een 2D-array van 4 x 5 door mee te geven dat er 4 kolommen moeten zijn. Numpy berekent zelf dat er dan 5 rijen zullen zijn.

```
a = np.array([1,2,3,4,5,6])
a.reshape(3,2)                # met de methode, en expliciet 
a.reshape(3,-1)               # met de methode en Numpy zoekt het zelf wel uit
np.reshape(a,(3,-1))          # kan ook met de functie, nieuwe dimensie is tuple

# Let op: hierboven a is hier nog steeds hetzelfde, want je hebt niets toegekend aan a

a = a.reshape(3,-1)           # nu is a wel aangepast
a = np.reshape(a,(3,-1))      # of kan ook met de functie
```

Maak een array `a` van getallen met de functie met 100 oplopende getallen van 1 t.e.m. 100 (gebruik een `range`). Transformeer deze naar een matrix `b` van 10 x 10, transformeer deze vervolgens naar een 3D-array `c` met dimensies 10 x 5 x 2.


In [2201]:
# 1
a = np.array(range(1,101))
print(a)
print(a.shape)
#
print()
# 2
b = a.reshape(10,10)
print(b)
print(b.shape)
#
print()
# 3
c = b.reshape(10,5,2)
print(c)
print(c.shape)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
(100,)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
(10, 10)

[[[  1   2]
  [  3   4]
  [  5   6]
  [  7   8]
  [  9  10]]

 [[ 11  12]
  [ 13  14]
  [ 15  16]
  [ 17  18]
  [ 19  20]]

 [[ 21  22]
  [ 23  

Maak een array `x` met met de functie `np.arange(1,5)`. Maak een array `y` met `np.ones(5)`.
Probeer beide arrays bij elkaar op te tellen, zodat je een array krijgt van `(4,5)`.

In [2202]:
x = np.arange(1,5)
y = np.ones(5)
print(x)
print(x.shape)
print() # /n
print(y)
print(y.shape)
print() # /n
y = y.reshape((5,1))
print(y)
print(y.shape)
print() # /n
z = x + y
print(z)
print(z.shape)

[1 2 3 4]
(4,)

[1. 1. 1. 1. 1.]
(5,)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]
(5, 4)


Zoals eerder vermeld kunnen we arrays niet zomaar groter of kleiner maken, maar er zijn we functies waarmee we dit kunnen doen: we kunnen arrays aan elkaar **kleven**. Je kan dit ook realiseren met basis Python code en met de Pandas library (zie andere oefenboekjes), maar soms is het gewoon veel handiger om dit gewoon met Numpy te doen en daarna pas met Pandas aan te slag te gaan (zoals je zal leren is Pandas gebouwd op Numpy arrays).

De belangrijkste Numpy functies zijn:

```
np.stack(lijst van arrays, richting waarin we stapelen)       # algemene functie
np.hstack(lijst van arrays)                                   # horizontaal stapelen
np.vstack(lijst van arrays)                                   # verticaal stapelen
np.concatenate(lijst van arrays, richting waarin we plakken)  # algemene functie
```

Al deze functie nemen de originele arrays als input en bouwen voor jou een volledig nieuwe array met de juiste vorm.


Maak met de functie `np.zeros` een array `a` van 10 nullen en een variabele `b=1`. Maak een array `c` die de som is van `a + b + 1` (hier wordt broadcasting gebruikt natuurlijk).

Plak `a`, `b` en `c` achter elkaar en boven elkaar. 

*Let op: voor `b` ga je nog wel iets extra moeten ondernemen (zie Numpy-functie hierboven om `b` langer te maken)* 

In [2203]:
# 1
a = np.zeros(10)
print(a)
print(a.shape)
#
print()
# 2
b = 1
print(b)
#
print()
# 3
c = a + b + 1
print(c)
print(c.shape)
#
print()
# 4.2
d = np.hstack([a,b,c])
print(d)
print(d.shape)
#
print()
# 4.2
e = np.vstack([d,d])
print(e)
print(e.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)

1

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
(10,)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
(21,)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]
(2, 21)


### Oefening 5 - Nog enkele nuttige truukjes

Het kan gebeuren dat je twee arrays elementgewijs moet **vermenigvuldigen** en dan de **som** moet maken van die producten. In spreadsheet software heet deze functie vaak SUMPRODUCT of iets dergelijks.

**Voorbeeld**
Voor Programmeren 1 zijn gewichten van de vakken als volgt verdeeld:
* OO - Concepten 1: 0.17 (17%)
* OO - Concepten 1: 0.38 (38%)
* Java FX: 0.45 (45%)

Student Milan haalt volgende scores: `[13,8,10]`. 

Op dit punt ken je voldende Numpy functie om dit op te lossen met enkele regels code.

```
gewichten = np.array([0.17,0.38,0.45])
milan = np.array([13,9,10])                          
np.sum(gewichten * milan)                   # broadcasting + np.sum functie gebruiken
(gewichten * milan).sum()                   # kan ook met broadcasting + sum-methode gebruiken 
```

Is hij geslaagd voor Programmeren 1?


In [2204]:
gewichten = np.array([0.17,0.38,0.45])
milan = np.array([13,9,10])
resultaat = np.sum(gewichten * milan)

if resultaat >= 10:
    print("Geslaagd :)")
else: print("Niet geslaagd :(")

Geslaagd :)


De functie `np.dot` kan dit in één keer berekenen. Het vermenigvuldigt en telt op. Het werkt ook gewoon op Python lists, de omzetting naar Numpy arrays gebeurt achter de schermen.

```
np.dot([0.17,0.38,0.45],[13,9,10])
```

Dat lijkt misschien niet meteen mega specatulair maar meestal doen er wel meer studenten mee aan een examen. Veronderstel dat we nu alle punten van de studenten hebben in een Python lijst van een lijst of 2D Numpy array.

```
gewichten = np.array([0.17,0.38,0.45])
punten = np.array([
                   [13,9,10],
                   [12,10,10],
                   [9,7,np.NaN],         # deze student heeft JavaFX niet afgelegd, np.NaN (Not A Number)
                   [10,7,12],
                   [8,9,10]]
                  )              
np.dot(punten, gewichten)                # bereken alle totaalpunten
np.dot(gewichten,punten.transpose())     # idem, maar punten moeten getransponeerd worden
```

Met de `transpose` methode (en functie) kun je de rijen in kolommen veranderen en vice versa. Deze heb je ook zo nu en dan eens nodig. Hier is het nodig als je de argumenten verwisselt van plaats, omdat `np.dot` eigenlijk een matrix-operatie is uit de wiskunde. Sommige studenten zullen deze leerstof in het middelbaar zeker gekregen hebben. 

In [2205]:
gewichten = np.array([0.17,0.38,0.45])
punten = np.array([
                   [13,9,10],
                   [12,10,10],
                   [9,7,np.NaN],         # deze student heeft JavaFX niet afgelegd, np.NaN (Not A Number)
                   [10,7,12],
                   [8,9,10]]
                  )
np.dot(punten, gewichten)                # bereken alle totaalpunten
np.dot(gewichten,punten.transpose())     # idem, maar punten moeten getransponeerd worden
# VB.
# 0.17 * 13 = x
# 0.17 * 12 = y
# x + y

array([10.13, 10.34,   nan,  9.76,  9.28])

De kans dat je met een dobbelsteen een bepaald aantal ogen gooit, is gelijk aan $\frac{1}{6}$

Hoeveel ga je gemiddeld gooien als je heel veel dobbelstenen zou opwerpen?

In [2206]:
# De kans dat je met een eerlijke dobbelsteen een bepaald aantal ogen gooit, is gelijk aan 1/6, omdat er zes mogelijke uitkomsten zijn en elke uitkomst even waarschijnlijk is.

# Als je heel veel dobbelstenen zou opwerpen, dan zou het gemiddelde aantal ogen dat je gooit dichter bij het verwachte gemiddelde van de verdeling komen. Het verwachte gemiddelde van de verdeling van de som van n dobbelstenen is gelijk aan n keer het verwachte gemiddelde van de verdeling van één dobbelsteen, oftewel n*(1+2+3+4+5+6)/6 = n*3.5.

# Dus als je heel veel dobbelstenen zou opwerpen, zou het gemiddelde aantal ogen dat je gooit dicht bij n*3.5 komen. Dit betekent dat als je bijvoorbeeld 100 dobbelstenen opwerpt, het gemiddelde aantal ogen dat je gooit dicht bij 350 zou komen. Echter, het is belangrijk om op te merken dat het werpen van een grote hoeveelheid dobbelstenen niet noodzakelijkerwijs betekent dat het resultaat precies gelijk zal zijn aan het verwachte gemiddelde, omdat er altijd variatie zal zijn in de resultaten.

Numpy bevat nog vele andere functies en methoden die je kan gebruiken. We lijsten er hier nog enkele voor je op. Probeer ze zelf uit op enkele arrays, meestal zegt de naam al voldoende. Soms bestaan ze als functie, soms als methode, en soms als beide.

* `mean()`
* `nansum()` , som zonder NaN-waarden 
* `prod()`
* `max()`
* `min()`
* `cumsum()`
* `sin()`, `cos()`, ... `exp()`
* ...

De lijst is veel te lang om hier op te sommen, maar je kan er quasi zeker vanuit gaan dat jouw probleem al door iemand anders is opgelost.Dus probeer het warmwater niet opnieuw uit te vinden, maar raadpleeg de documentatie. 

Hier is een mooie lijst van functies: https://numpy.org/doc/stable/reference/routines.html.  We zullen gaandeweg nog veel meer functies en truukjes leren.

### Oefening 6 - Numpy arrays uit bestanden

Je kan ook Numpy arrays maken op basis van gegevens uit tekstbestanden. Hieronder zie je een voorbeeld van hoe dit werkt op de dataset `tabel.csv`.
```python
data = np.genfromtxt('../datasets/tabel.csv',
                     delimiter=',',                             # delimiter teken kiezen
                     usecols=range(1,5),                        # welke kolommen willen inlezen
                     skip_header=1)                             # eerste kolom is header dus skippen
data
```
Probeer dit een keertje uit en bekijk het resultaat. Wat zijn de datatypes? Bekijk de shape.
Wat is het type van de variabele `data`?

In [2207]:
# data = np.genfromtxt("tabel.csv",
#                      delimiter=',',
#                      usecols=range(0,5))
# print(data)
data = np.genfromtxt("tabel.csv",
                     delimiter=',',                             # delimiter teken kiezen
                     usecols=range(1,5),                        # welke kolommen willen inlezen
                     skip_header=1)                             # eerste kolom is header dus skippen
# Probeer dit een keertje uit en bekijk het resultaat.
print(data)
# Wat zijn de datatypes?
print(data.dtype)
# Bekijk de shape.
print(data.shape)
# Wat is het type van de variabele data?
print(type(data))

[[ 1.         15.         54.         36.5       ]
 [ 2.         18.         68.         37.09999847]
 [ 3.         11.         41.         36.40000153]
 [ 4.         17.         59.         37.20000076]
 [ 5.         20.         65.         36.90000153]]
float64
(5, 4)
<class 'numpy.ndarray'>


Een andere manier om de gegevens in te lezen, is de volgende waarbij je ook namen van kolommen opgeeft, en optioneel ook enkele datatypes.

```python
import numpy as np
data = np.genfromtxt('../datasets/tabel.csv',
                     delimiter=',',                             # delimiter teken kiezen
                     usecols=range(1,5),                        # welke kolommen willen inlezen
                     skip_header=1,                             # eerste kolom is header dus skippen
                     names=['id','leeftijd','gewicht','temp'],  # we kunnen namen geven aan de kolommen
                     dtype=[int, int, float, float])            # we kunnen data types meegeven
```

Probeer dit ook een keertje uit. Bekijk het resultaat. Wat zijn de datatypes? Bekijk de shape.

Wat is het type van de variabele `data`?
Welke verschillen zijn er met de vorige manier van inlezen? Kijk goed.

In [2208]:
data = np.genfromtxt('tabel.csv',
                     delimiter=',',                             # delimiter teken kiezen
                     usecols=range(1,5),                        # welke kolommen willen inlezen
                     skip_header=1,                             # eerste kolom is header dus skippen
                     names=['id','leeftijd','gewicht','temp'],  # we kunnen namen geven aan de kolommen
                     dtype=[int, int, float, float])            # we kunnen data types meegeven

# Probeer dit een keertje uit en bekijk het resultaat.
print(data)
# Wat zijn de datatypes?
print(data.dtype)
# Bekijk de shape.
print(data.shape)
# Wat is het type van de variabele data?
print(type(data))

[(1, 15, 54., 36.5       ) (2, 18, 68., 37.09999847)
 (3, 11, 41., 36.40000153) (4, 17, 59., 37.20000076)
 (5, 20, 65., 36.90000153)]
[('id', '<i4'), ('leeftijd', '<i4'), ('gewicht', '<f8'), ('temp', '<f8')]
(5,)
<class 'numpy.ndarray'>


De tweede manier van inlezen levert een heterogene Numpy array -ook wel structured array genoemd-, die nu bestaat uit een lijst van tuples i.p.v. een lijst van een lijst. Daardoor kan je nu ook werken met de kolomnamen om te indexeren.

```python
data['id']
```
Test uit.

In [2209]:
print(['id'])
# Hier hebben we de kolom 'id' geïndexeerd, die we hebben gedefinieerd in het CSV-bestand. De functie np.recfromcsv() creëert een gestructureerde array, die bestaat uit een lijst van tuples, waarbij elke tuple overeenkomt met een rij in het bestand. De kolommen worden geïndexeerd op basis van hun naam in plaats van hun positie in de array.

# Door data['id'] te gebruiken, krijgen we de kolom 'id' als NumPy-array.

['id']
