In [ ]:
import pandas as pd
import numpy as np

# Opgaven op Python, Numpy en Pandas
In de opgaveboekjes is het de bedoeling dat je zelf eerst goed zoekt, en wroet om oplossingen te vinden. Dit is de beste manier om veel bij te leren.

## Vraag 1
Maak een Pandas tabel met 4 kolommen.
* id: 1, 2, 3, 4, 5
* leeftijd: 15, 18, 11, 17, 20
* gewicht: 54, 68, 41, 59, 65
* temp: 36.5, 37.1, 36.4, 37.2, 36.9

Je kunt deze aanmaken op verschillende manieren, hoe meer je er vindt, hoe beter je de leerstof onder de knie hebt.

Enkele begrippen die je kunnen leiden in je zoektocht:
* een Python dictionary met Python lists
* een Python dictionary met Pandas Series
* een 2D - Numpy array

In [ ]:
df1=pd.DataFrame([{"id":1,"leeftijd":15,"gewicht":54,"temp":36}, {"id":2,"leeftijd":18,"gewicht":68,"temp":37.1}f1=])
print(df1)

   id  leeftijd  gewicht  temp
0   1        15       54  36.0
1   2        18       68  37.1


In [14]:
arr=np.array([[1,2,3,4,5],[15,18,11,17,20],[54,68,41,59,65],[36.5,37.1,36.4,37.2,36.9]])
arr1=np.transpose(arr)
print(arr1)

[[ 1.  15.  54.  36.5]
 [ 2.  18.  68.  37.1]
 [ 3.  11.  41.  36.4]
 [ 4.  17.  59.  37.2]
 [ 5.  20.  65.  36.9]]


In [13]:
df2=pd.DataFrame(arr1,columns=["id","leeftijd","gewicht","temp"])
print(df2)

    id  leeftijd  gewicht  temp
0  1.0      15.0     54.0  36.5
1  2.0      18.0     68.0  37.1
2  3.0      11.0     41.0  36.4
3  4.0      17.0     59.0  37.2
4  5.0      20.0     65.0  36.9


In [15]:
ls=[[1,15,54,36.5], [2,18,68,37.1]]
df3=pd.DataFrame(ls,columns=["id","leeftijd","gewicht","temp"])
print(df3)

   id  leeftijd  gewicht  temp
0   1        15       54  36.5
1   2        18       68  37.1


In [ ]:
ls=[[1,15,54,36.5], [2,18,68,37.1]]
df3=pd.DataFrame(ls,columns=["id","leeftijd","gewicht","temp"])
print(df3)

   id  leeftijd  gewicht  temp
0   1        15       54  36.5
1   2        18       68  37.1


In [16]:
df4=pd.DataFrame({"id":[1,2,3,4,5],"leeftijd":[15,18,11,17,20],"gewicht":[54,68,41,59,65],"temp":[36.5,37.1,36.4,37.2,36.9]})
print(df4)

   id  leeftijd  gewicht  temp
0   1        15       54  36.5
1   2        18       68  37.1
2   3        11       41  36.4
3   4        17       59  37.2
4   5        20       65  36.9


## Vraag 2
Haal de 2e kolom uit de tabel. Hier zijn heel veel mogelijkheden om te doen.
Bekijk per mogelijkheid ook welke Python type het is. Vind je ze alle 7?

In [ ]:
# hier komt jouw code

In [ ]:
# hier komt jouw code

In [ ]:
# hier komt jouw code

In [ ]:
# hier komt jouw code

In [ ]:
# hier komt jouw code

In [ ]:
# hier komt jouw code

In [ ]:
# hier komt jouw code

In [ ]:
# hier komt jouw code

## Vraag 3
Haal de 3e rij uit de tabel

In [ ]:
# hier komt jouw code

## Vraag 4
Bereken de minimum- en maximumleeftijd

In [ ]:
# hier komt jouw code

## Vraag 5
Bereken de som van alle gewichten en deel die door het aantal gewichten

In [ ]:
# hier komt jouw code

## Vraag 6
Deel alle gewichten door 1000

In [ ]:
# hier komt jouw code

## Vraag 7
Zet alle temperaturen om naar Fahrenheit

In [ ]:
# hier komt jouw code

## Vraag 8
Bewaar de tabel in een bestand

In [ ]:
# hier komt jouw code

## Vraag 9
Open de tabel in PyCharm als een datatabel (tabblad Data onderaan), verander er iets aan en bewaar terug.

In [ ]:
# hier komt jouw code

## Vraag 10
Lees de tabel terug uit het bestand

In [ ]:
# hier komt jouw code

## Vraag 11
Verwijder de kolom “id”

In [ ]:
# hier komt jouw code

## Vraag 12
Voeg een kolom “lengte” toe met gegevens: 160, 175, 162, 169, 179

In [ ]:
# hier komt jouw code

## Vraag 13
Bereken de BMI van iedere persoon in de tabel

In [ ]:
# hier komt jouw code

## Vraag 14
Voeg deze BMI als kolom toe aan de tabel

In [ ]:
# hier komt jouw code

## Vraag 15
Behoud alleen de gewichten die kleiner of gelijk zijn aan 60 uit de kolom gewicht.

In [ ]:
# hier komt jouw code

## Vraag 16
Vervang in de kolom leeftijd alle leeftijden groter of gelijk aan 18 door 19

In [ ]:
# hier komt jouw code

## Vraag 17
Vind alle temperaturen van de personen die ouder zijn dan 16 jaar

In [ ]:
# hier komt jouw code